app:
  ind:
    slotsUrl: "https://oap.ind.nl/oap/api/desks/AM/slots/?productKey=DOC&persons=1"
    bookingUrl: "https://oap.ind.nl/oap/api/desks/AM/appointments/"
  mail:
    recipient:
  customer:
    phone:
    email:
    vNumber:
    firstName:
    lastName:

server:
  port: 8080

management:
  server:
    port: 8008
    ssl.enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
endpoints:
  shutdown:
    enabled: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties.mail.smtp:
      auth: true
      starttls.enable: true